# Generated by Django 5.1.3 on 2024-11-17 04:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="receipt",
            options={},
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="ipfs_hash",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="tax_amount",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="total_amount",
        ),
        migrations.RemoveField(
            model_name="receiptitem",
            name="category",
        ),
        migrations.RemoveField(
            model_name="receiptitem",
            name="quantity",
        ),
        migrations.AddField(
            model_name="receipt",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="receipts/"),
        ),
        migrations.AddField(
            model_name="receipt",
            name="raw_response",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="subtotal",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="tax",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="store_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="receiptitem",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
