# Generated by Django 5.1.3 on 2024-11-17 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receipts_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receiptitem",
            old_name="date",
            new_name="purchase_date",
        ),
    ]
