# Generated by Django 5.1.3 on 2024-11-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts_api', '0002_rename_date_receiptitem_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptitem',
            name='category',
            field=models.CharField(default='food', max_length=255),
        ),
    ]
